# Site settings
title: Jeff Lewis
email: mail@jeffreylewis.me
description: > # this means to ignore newlines until "baseurl:"
  learning, every day.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffreylewis.github.io" # the base hostname & protocol for your site
twitter_username: jeffrey_allen
github_username:  jeffreylewis

# Build settings
markdown: kramdown

gems:
  - jemoji
  - jekyll-redirect-from