# Site settings
title: Jeff Lewis
name: Jeff Lewis
email: mail@jeffreylewis.me
description: > # this means to ignore newlines until "baseurl:"
  learning, every day.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jeffreylewis.me" # the base hostname & protocol for your site
twitter_username: jeffrey_allen
github_username: jefflewis
linkedin_username: lewisj88

# Build settings
markdown: kramdown
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _scss
  style: :compressed

gems:
  - jemoji
  - jekyll-redirect-from
